sudo: required
services:
    - docker

before_install:
    - docker build -t jlee12/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jlee12/react-test npm test

after_success:
    - docker build -t jlee12/multi-client ./client
    - docker build -t jlee12/multi-nginx ./nginx
    - docker build -t jlee12/multi-server ./server
    - docker build -t jlee12/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
    # Taker those images and push them to docker hub
    - docker push jlee12/multi-client
    - docker push jlee12/multi-nginx
    - docker push jlee12/multi-server
    - docker push jlee12/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-321224189992
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
